# Generated by Django 3.2.25 on 2025-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_img_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_Json', models.CharField(max_length=5000)),
                ('amount', models.IntegerField(default='')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=500)),
                ('oid', models.CharField(max_length=500)),
                ('amountpaid', models.CharField(max_length=500)),
                ('paymentstatu', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=500)),
                ('delivered', models.BooleanField(default='False')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
