# Generated by Django 5.1.7 on 2025-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_orders_paymentstatu_orders_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amountpaid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items_Json',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paymentstatus',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
